### PR TITLE
Fix missing statement_parts for index definitions

### PR DESCRIPTION
**Pull request by januszm**

### CODE REVIEW

**Comment by januszm** [comment]
@teeparham  Please create a branch for 1.1.0 tag so I can update the Pull Request. My changes were built on top of v1.1.0 tag.

**Comment by teeparham** [comment]
There is a 1.0 branch, for which the head is currently version 1.2 - can you use that as the base of the PR?

**Comment by januszm** [comment]
I see, at first I thought that 1.0 matches v1.0.0 but I didn't check that, sorry. It seems that I may have problems with it though, I remember some issues with usage of 'quote' method, which was added afair here: https://github.com/rgeo/rgeo-activerecord/commit/cef537195d4869719d47e946fad0b7e4eec32c84

I need to check if branch 1.0 is compatible with ActiveRecord 4.0/4.1 tomorrow.

**Comment by januszm** [comment]
@teeparham I've just updated the pull request. I don't remember what issues I had with branch 1.0 and ActiveRecord 4.1 in the past but it seems that it is all right now (perhaps I used wrong gemset, whatever ...). This looks good to go, I took the code from Rails 4.2

**Comment by teeparham** [comment]
Are these fixes for ActiveRecord 4.0/4.1, or for 4.2? If they're for 4.2+, then please rebase these commits onto the latest master. If they're for 4.0/4.1, then please change the target of the merge from master to the 1.0 branch.

`rgeo-activerecord` version 1.2.0 is the head of the 1.0 branch, which works with AR 4.0/4.1.

`rgeo-activerecord` version 4.x is the head of the master branch, which works with AR 4.2+, and has breaking changes that don't work with AR < 4.2 .

**Comment by januszm** [comment]
These are fixes for AR 4.0/4.1 so branch I think that I need to create another pull request unless you know how to change the target of the merge here on this page.

**Comment by teeparham** [comment]
Hmm... I don't see how to change the target. You might have to close this PR & submit a new one with a different base branch.

**Pull request closed without merging**
