### PR TITLE
`DepthFirst` visitor is no longer part of Rails 6.1

### PR DESCRIPTION
**Pull request by kamipo**
Ref https://github.com/rails/rails/pull/36492.

### CODE REVIEW

**Comment by oyeanuj** [comment]
Thanks @kamipo! 

@teeparham Is this good to merge?

**Comment by fuxx** [comment]
Is that merge request still alive?

**Comment by keithdoggett** [comment]
Thanks for bringing this up @kamipo . 

Instead of using version-specific conditionals, it would be better if the `Arel::Visitors::DepthFirst.class_eval` block is removed altogether, we add an appraisal for `activerecord 6.1` (based on the master branch of `rails`), and then bump the gem version.

This would be consistent with how the gem has been versioned up to this point.

**Comment by keithdoggett** [comment]
Closing since #57 was merged.

**Pull request closed without merging**
