### PR TITLE
Fixing issues #63

### PR DESCRIPTION
**Pull request by hiromipaw**
Hi,
I thought this would fix issues #63: https://github.com/rgeo/activerecord-postgis-adapter/issues/63
So it would be possible to call:

    self.lonlat = Pin.rgeo_factory_for_column(:latlon).point(self.longitude, self.latitude)

Instead of:

     self.lonlat = Pin.rgeo_factory_for_column(:latlon, {}).point(self.longitude, self.latitude)

Let me know.

Silvia

### CODE REVIEW

**Comment by phlegx** [comment]
:+1:

**Comment by teeparham** [comment]
This looks good, except for the extra commits. Would you mind removing all the commits except https://github.com/nopressurelabs/rgeo-activerecord/commit/d6b2d483820ef83 & amending it to not have the .gitignore change?

You should globally ignore the `.idea` directory in your `~/.gitignore` - it doesn't need to be part of this projects' .gitignore.

**Comment by hiromipaw** [comment]
Hey guys. 
Sorry this got polluted with some .gitignore stuff. I had not realised to be honest. I have cleaned that now.

**Comment by teeparham** [comment]
Thank you for cleaning up the commit history. It looks like there is a failing test. You can run the tests locally with `rake`.

**Comment by hiromipaw** [comment]
Let me know what you think. :)

**Comment by teeparham** [comment]
Thank you. This looks like an improvement to me. 

Is anyone using the syntax in the test? It seems bizarre to me:

Old syntax (which would be made invalid with this PR):

```ruby
factory = MyTable.rgeo_factory_for_column(:hello).call(has_z_coordinate: true, srid: 4326)
```

New syntax:

```ruby
factory = MyTable.rgeo_factory_for_column(:hello, has_z_coordinate: true, srid: 4326)
```

This is a breaking change & would require a major version release. It may break adapters that use this gem.

In related news, given the changes in ActiveRecord 4.2, the entire idea of caching factories on the Model class is likely going to be removed. See https://github.com/rgeo/activerecord-postgis-adapter/issues/163

**Comment by hiromipaw** [comment]
I am not sure, to be honest in all the docs I have always read the "new syntax"... The next test in line also uses it (not modified by me). That's why I just changed the test, I thought it was some old baggage...

**Comment by teeparham** [comment]
The factory code has been re-written (and this method was removed) since version 3.0, so I'm closing this.

**Pull request closed without merging**
